train_data_path: '../train.json'
dev_data_path: '../dev.json'
test_data_path: '../test.json'
model_name: "bert-base-uncased"
NUM_EPOCHS: 1
TRAIN_BATCH_SIZE: 64
VAL_BATCH_SIZE: 64
TEST_BATCH_SIZE: 1
LEARNING_RATE: "1e-5"